# Drop-in replacement for EXPECTED_OUTLINE in tests/test_course_structure.py
# Also update the count assertion: == 75 (was 64)

EXPECTED_OUTLINE = [
    "1. From a Sentence to a Training Example",
    "2. What You Will Build: The Spec, the Cost, and the Nine Stages",
    "3. Run the Whole Pipeline Once Before Understanding It",
    "4. How Computers Store Characters as Agreed Numbers",
    "5. Unicode Code Points and UTF-8 Bytes",
    "6. Why Visually Similar Text Needs Normalization",
    "7. Inspecting Real Text: Invisible Characters and Cleaning Decisions",
    "8. Tokens and Token IDs",
    "9. Why Byte-Level Tokenization Works",
    "10. How BPE Learns Frequent Merges",
    "11. Vocabulary Size and Special Tokens",
    "12. Training the Repository Tokenizer",
    "13. Unicode Round Trips and the Complete Byte Alphabet",
    "14. Tokenizer Reports, Compression, and Failure Tests",
    "15. EOS Tokens and Packed Document Streams",
    "16. Context Windows, Shifted Targets, and Batches",
    "17. Tensors and Shapes Without Fear",
    "18. What a Parameter Is: Fitting a Line by Hand",
    "19. Linear Layers, Matrix Multiplication, and Nonlinearity",
    "20. One Training Step: Forward, Loss, Backward, Update",
    "21. Turning Token IDs Into Embeddings",
    "22. Logits and Next-Token Probabilities",
    "23. Cross-Entropy Loss With Small Numbers",
    "24. Training a Model Without Attention, and Where It Fails",
    "25. Training Loss, Validation Loss, and Overfitting",
    "26. Why Tokens Need to Look at Other Tokens",
    "27. Queries, Keys, and Values",
    "28. Dot Products, Scaling, and Attention Softmax",
    "29. Causal Masks and Weighted Value Mixing",
    "30. Heads, Reshaping, Transposing, and the Output Projection",
    "31. Why Tokens Need Position Information",
    "32. RoPE Rotations and Relative Position Math",
    "33. Residual Connections and RMSNorm",
    "34. MLPs, Activations, and SwiGLU Gates",
    "35. One Complete Block and a Stack of Blocks",
    "36. Weight Initialization and Tied Embeddings",
    "37. Tracing Shapes and Counting Parameters Through the Whole Model",
    "38. Computation Graphs, Gradients, and the Chain Rule",
    "39. SGD and Learning Rate",
    "40. Momentum, Adam, and AdamW",
    "41. Weight Decay and Optimizer Parameter Groups",
    "42. Warmup, Cosine Decay, and Gradient Accumulation",
    "43. FP32, FP16, and BF16, and Why a T4 Must Use FP16",
    "44. Autocast and Gradient Scaling",
    "45. Clipping, Inf, NaN, and Skipped Updates",
    "46. Documents, Corpora, JSON, and JSONL",
    "47. Choosing a Dataset: Licence, Provenance, and a Pinned Revision",
    "48. Data-Quality Filters and Rejection Reasons",
    "49. Exact Deduplication and Benchmark Contamination",
    "50. Stable Dataset Splits, Manifests, and Fingerprints",
    "51. Binary Shards, Dtypes, Memory Mapping, and Shard Sampling",
    "52. What a Complete Checkpoint Saves",
    "53. Seeds, RNG State, and Reproducibility",
    "54. Safe Resume and Artifact Compatibility",
    "55. Setting Up Colab, CUDA, and Persistent Drive Storage",
    "56. Estimating Memory and Benchmarking the Batch",
    "57. Running the Preflight and Reading Its Report",
    "58. Tracking a Run: Logs, Metrics, and Experiment Records",
    "59. The Twenty-Step Smoke Test",
    "60. The Ten-Million-Token Pilot and Go/No-Go Review",
    "61. Training to the Full Token Budget and Surviving Disconnects",
    "62. Greedy Decoding and Why It Repeats",
    "63. Temperature, Top-k, and Top-p Sampling",
    "64. Running the Chat Script and Why Generation Is Slow",
    "65. Evaluating Loss, Perplexity, and Fixed Prompts",
    "66. Multiple-Choice Tasks and Accuracy",
    "67. Reading Samples Without Fooling Yourself",
    "68. Debugging Loss, NaNs, OOM, Repetition, and Resume Failures",
    "69. What a 59M-Parameter Model Can and Cannot Do",
    "70. Token Budgets, Scaling Laws, and Being Under-Trained",
    "71. Scaling Width, Depth, Data, Context, and Compute",
    "72. What Post-Training Would Add: SFT and Chat Templates",
    "73. Designing Your Own Experiment",
    "74. Writing a Model Card and Publishing Your Run",
    "75. Explaining Technical Ideas Without Hidden Jargon",
]
